spring.application.name=learning
spring.datasource.url=jdbc:mysql://localhost:3306/gamified_learning
spring.datasource.username=root
spring.datasource.password=Aditi007#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true